# Generated by Django 3.2.5 on 2021-07-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='dias',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
