# Generated by Django 3.2.5 on 2021-07-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='descripcion',
            field=models.TextField(default='Sin descripción establecida.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='requisitos',
            field=models.TextField(default='Sin requisitos adicionales.', max_length=500),
        ),
    ]
