# Generated by Django 3.2.5 on 2021-07-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='precio',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
