# Generated by Django 3.2.5 on 2021-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20210722_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='tours'),
        ),
    ]
